### PR TITLE
Move to typescript

### PR DESCRIPTION
**Pull request by garrettjstevens**
This converts the package from using JS to TS. I did this a while back for Apollo development and forgot to push this branch.

It also does a bit of cleanup like:
* Deduplicating prettier rules (now just in .prettierrc, previously was there and also in package.json and in .eslintrc)
* Fix documentation.js generation of API docs
* Bump min Node version to 10

### CODE REVIEW

**Comment by rbuels** [comment]
to be safe, let's do a major version bump when we release this

**Comment by cmdcolin** [comment]
I made a branch where i proposed some alternatives not requiring tsdx 
https://github.com/GMOD/gff-js/tree/proposed_tsc_modifications

it outputs both es2018 and es5 presets from typescript using it's '--target' flag. targetting --target esnext is a little too new apparently for create-react-app (balks on class properties) but --target es2018 is pretty modern

I think it is a great idea to output esm too, and reduces the need for excessive polyfilling/transpilation. My opinion is that it is not necessary to do bundling on the output for node modules though, so this is removed there. bundling is a concept that is useful on the client side, not for the server side.


also adds a clean step to build, ts-jest, and a couple other things. should not require a major version bump (installing the dev deps may require the user to have version 10+ of the code, but consumers would not, and so it does not require pushing the 10+ to the end user)

**Comment by garrettjstevens** [comment]
I'm fine with using that branch. This is a small library, so there aren't as many benefits of bundling, but I think there are cases (e.g. larger libraries with lots of targets) where bundling is useful. I found [this](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c) interesting article on why React uses Rollup as their bundler.

**Comment by cmdcolin** [comment]
thanks for accepting that :)

that article is also a good point of reference, but it is somewhat light on detail and doesn't address the premise that bundling might not be required for a library.

**Comment by cmdcolin** [comment]
random note: usage in gff3tabix

```

      const features = gff.parseStringSync(gff3, {
        parseFeatures: true,
        parseComments: false,
        parseDirectives: false,
        parseSequences: false,
      }) as FeatureLoc[][]
```

it complains that e.g. directives aren't matchable to featureloc, even though we say not to parse directives, so would now have to be casted to unknown and then back to featureloc after that, so hard to get the benefit of the typescript types there?

**Comment by garrettjstevens** [comment]
I just pushed a change that will correctly narrow down the type of feature based on the options passed in. It uses function overloads on the `parseStringSync` function, but since there are so many possible options, the overloads are unfortunately _very_ verbose (~300 lines total!) and hard to read. I wasn't sure how else to do it, though, and it seems to work.

**Comment by rbuels** [comment]
Wow. That is a lot of typescript. Fortunately we probably won’t have to change it much!

**Comment by cmdcolin** [comment]
nice...another thing that could benefit from this https://github.com/GMOD/generic-filehandle/issues/39

**Comment by garrettjstevens** [comment]
Things learned that may be applicable in the future when writing libraries. If you are changing the return type of a function based on options passed in:
- Try to keep the number of options minimal
- It's easier if all the options are required, e.g.
```ts
interace Options {
  parseFeatures: boolean
  parseDirectives: boolean
}
```
is easier to make overloads for than
```ts
interace Options {
  parseFeatures?: boolean
  parseDirectives?: boolean
}
```

**Pull request merged**
