### PR TITLE
fix unpolyfilled stream for webpack 5

### LINKED ISSUE #40: Kick fs module include out of browser bundle
Was done for generic-filehandle, bgzf-filehandle, etc.

### PR DESCRIPTION
**Pull request by smeng9**
Closes https://github.com/GMOD/gff-js/issues/40#issuecomment-957109290

### CODE REVIEW

**Comment by cmdcolin** [comment]
thanks for this PR, this may be a good option! the other option i have considered is making a parseStringSync function that does not use any streams but that might be a larger refactor

**Comment by garrettjstevens** [comment]
If someone uses this in Webpack 4, will it use the Webpack polyfill for stream or `stream-browserify`?

**Comment by smeng9** [comment]
@garrettjstevens I believe Webpack polyfill for stream and stream-browserify is the same. Seem webpack source code https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/ModuleNotFoundError.js#L28

So it should be safe to use for Webpack 4 if you have any legacy code relying on it.

**Comment by smeng9** [comment]
@cmdcolin The previous CI pipeline failed because I forgot to commit yarn.lock file. Can you take a look again?

**Comment by cmdcolin** [comment]
let's give it a go :)

**Comment by cmdcolin** [comment]
published as 1.3.0, hope that helps!

**Pull request merged**
