### PR TITLE
Add trimming of attribute names and values in GFF3

### PR DESCRIPTION
**Pull request by cmdcolin**
Follow up to the JBrowse flatfile-to-json.pl PR to trim whitespace surrounding GFF3 attribute keys and values

### CODE REVIEW

**Comment by cmdcolin** [comment]
I think hopefully this should be good to go...I'll merge it and bump version :)

**Comment by rbuels** [comment]
It probably would have been better to leave the treatment of whitespace up to the code that consumes this module, cause the whitespace thing is more of an opinion than part of the spec. But it's merged now and this is relatively minor, so I guess we'll see if this causes anyone problems.

**Comment by cmdcolin** [comment]
I guess that could be true, I couldn't imagine any scenario where it is desirable to keep it though. The scenario that seemed maybe of interest for parsing purposes was the strict parsing of things like commas as multi-value separators and requiring urlencoded stuff...that was something that I changed a test for in this PR in fact :)

**Comment by cmdcolin** [comment]
Are you able to imagine any scenario where it's desirable to keep ?

**Comment by sammyjava** [comment]
I've never seen a gene identifier or any other genomic feature identifier with a space inside. That would break lots of apps.

**Comment by cmdcolin** [comment]
good to know, I guess even spaces inside an identifier would be allowed, the main thing that this PR did was trim trailing/preceding whitespace e.g.

```
  value = blah   ; test=  1,2,  4;
```

gives us

```
{ "value": "blah", "test": ["1","2","4"] }
```

whereas previously it was incorporating the spaces into the keys and values

**Pull request merged**
